# COMMENT: redirect rules with all the fields expanded
# According to netlify domain management
# https://app.netlify.com/sites/libjohn/settings/domain#domains
# # Redirect default Netlify subdomain to primary domain
# https://libjohn.netlify.com/* https://www.johnlittle.info/:splat 301!
[[redirects]]
  from = "https://libjohn.netlify.com/*"
  to = "https://www.johnlittle.info/:splat"
  status = 301
  force = true
  
  
# According to netlify domain management
# https://app.netlify.com/sites/libjohn/settings/domain#domains
# # These extra rules are required because HTTPS is not forced
# http://libjohn.netlify.com/* https://www.johnlittle.info/:splat 301!
[[redirects]]
  from = "http://libjohn.netlify.com/*"
  to = "https://www.johnlittle.info/:splat"
  status = 301
  force = true
  
# COMMENT: redirect rules with all the fields expanded
# According to netlify domain management
# https://app.netlify.com/sites/dukeslides/settings/domain#custom-domains
# Redirect default Netlify subdomain to primary domain
# http://dukeslides.netlify.com/* http://dukeslides.johnlittle.info/:splat 301!
[[redirects]]
  from = "/dukeslides/*"
  to = "https://dukeslides.johnlittle.info/:splat"
  status = 301
  force = true
  
# openrefine
[[redirects]]
  from = "/openrefine/*"
  to = "https://libjohn.github.io/openrefine/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://openrefine.johnlittle.info/*"
  to = "https://libjohn.github.io/openrefine/:splat"
  status = 301
  force = true
  
  # dsvil
  # openrefine
[[redirects]]
  from = "/dsvil/*"
  to = "https://dsvil.johnlittle.info/:splat"
  status = 301
  force = true
[[redirects]]
  from = "/dsvil2018/*"
  to = "https://dsvil.johnlittle.info/:splat"
  status = 301
  force = true